version: "3.9"

services:
  postgres:
    image: 'postgres:16'
    environment:
      - 'POSTGRES_DB=jotter-blog'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - "5432:5432"
    volumes:
      - jotter-volume:/var/lib/postgresql/
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  jotter-volume: { }